### FILE: tests/auth_v11_flex.http
### VERSION: 2.3.0
### DATE: 31-03-2026
### MÔ TẢ: Quy trình: Đăng ký -> Login (Chờ duyệt) -> Admin Login -> Phê duyệt -> Login (Thành công).

@baseUrl = https://gia-pha-backend.onrender.com/api

# 1. ĐĂNG KÝ TRỞ THÀNH CLAN_ADMIN (Mặc định status: CHO_DUYET)
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "password": "password123",
    "name": "Người Dùng Chờ Duyệt",
    "isNewClan": true,
    "clanName": "Họ A Phê Duyệt"
}

###

# 2. ĐĂNG NHẬP LẦN 1 (Kết quả: CHO_DUYET)
# @name login_pending
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "identifier": "abc@gmail.com",
    "password": "password123"
}

###

# 2.1 login với role = SYSTEM_ADMIN để phê duyệt cho CLAN_ADMIN
# @name login_system_admin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "identifier": "nguyenthanhq@gmail.com",
    "password": "France1989"
}

###

# 3. PHÊ DUYỆT (Token của System Admin)
# Thay {{targetUserId}} bằng ID từ kết quả bước 1
@targetUserId = {{register.response.body.data.userId}}
@adminToken = {{login_system_admin.response.body.token}} 

PUT {{baseUrl}}/auth/approve/{{targetUserId}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

###

# 4. KIỂM TRA LẠI THÔNG TIN SAU KHI DUYỆT
# Lúc này status phải là DA_DUYET và changed_by phải có giá trị
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "identifier": "abc@gmail.com",
    "password": "password123"
}