/**
 * PATH       : src/shared/errors/codes/onboarding.codes.js
 * DATETIME   : 2026-07-21T19:05:00+07:00
 * VERSION    : 1.0.0-CED-1.1
 * DESCRIPTION: Mã lỗi Onboarding Process (OPD v1.2).
 *              Cover: create case, profile, submit, review, approve/reject, branch, merge.
 *              Pure constants only — zero business import.
 */

'use strict';

const ONBOARDING = Object.freeze({
  // Case lifecycle
  CASE_NOT_FOUND: 'ONBOARDING_CASE_NOT_FOUND',
  CASE_NOT_EDITABLE: 'ONBOARDING_CASE_NOT_EDITABLE',
  CASE_INVALID_STATUS: 'ONBOARDING_CASE_INVALID_STATUS',
  CASE_ALREADY_SUBMITTED: 'ONBOARDING_CASE_ALREADY_SUBMITTED',
  CASE_ALREADY_APPROVED: 'ONBOARDING_CASE_ALREADY_APPROVED',
  CASE_ALREADY_REJECTED: 'ONBOARDING_CASE_ALREADY_REJECTED',
  CASE_CANCELLED: 'ONBOARDING_CASE_CANCELLED',
  CASE_EXPIRED: 'ONBOARDING_CASE_EXPIRED',

  // Profile & Member
  PROFILE_INCOMPLETE: 'ONBOARDING_PROFILE_INCOMPLETE',
  MEMBER_ALREADY_EXISTS: 'ONBOARDING_MEMBER_ALREADY_EXISTS',
  INVALID_CASE_TYPE: 'ONBOARDING_INVALID_CASE_TYPE',

  // Review / Decision
  REVISION_REQUIRED: 'ONBOARDING_REVISION_REQUIRED',
  REJECT_REASON_REQUIRED: 'ONBOARDING_REJECT_REASON_REQUIRED',
  NOT_UNDER_REVIEW: 'ONBOARDING_NOT_UNDER_REVIEW',

  // Branch & Merge
  BRANCH_NOT_ALLOWED: 'ONBOARDING_BRANCH_NOT_ALLOWED',
  BRANCH_NOT_FOUND: 'ONBOARDING_BRANCH_NOT_FOUND',
  MERGE_FAILED: 'ONBOARDING_MERGE_FAILED',
  MERGE_PRECONDITION: 'ONBOARDING_MERGE_PRECONDITION',
  MEMBER_LIMIT_EXCEEDED: 'ONBOARDING_MEMBER_LIMIT_EXCEEDED',

  // Permission
  NOT_CASE_OWNER: 'ONBOARDING_NOT_CASE_OWNER',
  ADMIN_REQUIRED: 'ONBOARDING_ADMIN_REQUIRED',
});

module.exports = ONBOARDING;