/**
 * PATH       : src/shared/errors/codes/security.codes.js
 * DATETIME   : 2026-07-21T19:05:00+07:00
 * VERSION    : 1.0.0-CED-1.1
 * DESCRIPTION: Mã lỗi Security Policy, Delegation, Lock Engine, RBAC nâng cao (SEC).
 *              Pure constants only — zero business import.
 */

'use strict';

const SECURITY = Object.freeze({
  // Policy & Authorization
  POLICY_VIOLATION: 'SECURITY_POLICY_VIOLATION',
  INSUFFICIENT_ROLE: 'SECURITY_INSUFFICIENT_ROLE',
  INSUFFICIENT_SCOPE: 'SECURITY_INSUFFICIENT_SCOPE',
  ACCESS_DENIED: 'SECURITY_ACCESS_DENIED',

  // Delegation (SEC điều khoản D)
  DELEGATION_NOT_FOUND: 'SECURITY_DELEGATION_NOT_FOUND',
  DELEGATION_EXPIRED: 'SECURITY_DELEGATION_EXPIRED',
  DELEGATION_REVOKED: 'SECURITY_DELEGATION_REVOKED',
  DELEGATION_INVALID_SCOPE: 'SECURITY_DELEGATION_INVALID_SCOPE',

  // Lock Engine
  ACCOUNT_TEMP_LOCKED: 'SECURITY_ACCOUNT_TEMP_LOCKED',
  ACCOUNT_PERM_LOCKED: 'SECURITY_ACCOUNT_PERM_LOCKED',
  UNLOCK_NOT_ALLOWED: 'SECURITY_UNLOCK_NOT_ALLOWED',

  // Other
  IP_BLOCKED: 'SECURITY_IP_BLOCKED',
  SUSPICIOUS_ACTIVITY: 'SECURITY_SUSPICIOUS_ACTIVITY',
});

module.exports = SECURITY;